// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGR-_0GeNPSODC8asSSPEZ1LXmMVy6rtk',
    appId: '1:54501462279:web:05564f8fdfdd335b1975a2',
    messagingSenderId: '54501462279',
    projectId: 'blogslikho',
    authDomain: 'blogslikho.firebaseapp.com',
    storageBucket: 'blogslikho.firebasestorage.app',
    measurementId: 'G-HXGV1H7E3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8ZYj_2JrQTyrhSDnM4fUTM0RAot63EHE',
    appId: '1:54501462279:android:b245011db04bf25f1975a2',
    messagingSenderId: '54501462279',
    projectId: 'blogslikho',
    storageBucket: 'blogslikho.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3fFu1Cy7B3cF2v9uZmfYn0gxBXK0-FCE',
    appId: '1:54501462279:ios:371a290bb3e301021975a2',
    messagingSenderId: '54501462279',
    projectId: 'blogslikho',
    storageBucket: 'blogslikho.firebasestorage.app',
    iosClientId: '54501462279-8chg4epaajavf0rpel4obnjjev3756dq.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogsPado',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3fFu1Cy7B3cF2v9uZmfYn0gxBXK0-FCE',
    appId: '1:54501462279:ios:371a290bb3e301021975a2',
    messagingSenderId: '54501462279',
    projectId: 'blogslikho',
    storageBucket: 'blogslikho.firebasestorage.app',
    iosClientId: '54501462279-8chg4epaajavf0rpel4obnjjev3756dq.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogsPado',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGR-_0GeNPSODC8asSSPEZ1LXmMVy6rtk',
    appId: '1:54501462279:web:93261d41da0aac491975a2',
    messagingSenderId: '54501462279',
    projectId: 'blogslikho',
    authDomain: 'blogslikho.firebaseapp.com',
    storageBucket: 'blogslikho.firebasestorage.app',
    measurementId: 'G-GH08CVRMHT',
  );

}